name: My First Workflow

on: push

jobs:
  myfirstjob:
    runs-on: self-hosted
    steps:
      - name: create a file
        run: echo "This is my first workflow" > myfirstfile.txt

      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: myfirstartifact
          path: myfirstfile.txt

  secondjob:
    runs-on: self-hosted
    needs: myfirstjob
    steps:
      - name: download artifact
        uses: actions/download-artifact@v3
        with:
          name: myfirstartifact

      - name: read the file
        run: cat myfirstartifact/myfirstfile.txt
         

      
        