name: My First Workflow

on: push

jobs:
  myfirstjob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4

      - name: list files
        run: ls -l
  mysecondjob:
    runs-on: ubuntu-latest
    needs: myfirstjob
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: check node version
        run: node -v
        